# This workflow will build a golang project, and it will also build the dockerfile if a new tag has been pushed and publish it to dockerhub
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sweng Analysis

on:
  push:
    branches: [ "main", api-queries ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main", api-queries ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variable
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Test environment variable
      run: echo ${{ env.RELEASE_VERSION }}


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -args ${{ secrets.GHAPI_ACCESS_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Build and push
      if: startsWith(github.ref, 'refs/tags/v')
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sweng_analysis:v${{ env.RELEASE_VERSION }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
